### ISSUE TITLE
A uncaught exception occured

### ISSUE THREAD

**Issue by andrebnc** [josecastroleon/pimatic-openweather#1]
Hello!

error [pimatic]: A uncaught exception occured: Error: socket hang up at createHangUpError (http.js:1472:15) at Socket.socketCloseListener (http.js:1522:23) at Socket.EventEmitter.emit (events.js:117:20) at TCP.close (net.js:466:12) This is most probably a bug in pimatic or in a module, please report it!
error [pimatic]: A uncaught exception occured: Error: connect ETIMEDOUT at errnoException (net.js:901:11) at Object.afterConnect [as oncomplete](net.js:892:19) This is most probably a bug in pimatic or in a module, please report it!

That is what i get a hundred times a day.

**Comment by sweetpi** [comment]
Should be fixed in newest release.
