### ISSUE TITLE
Imperial measurements still labelled as metric

### ISSUE THREAD

**Issue by dgmltn** [josecastroleon/pimatic-openweather#10]
Here's a sample from my devices array:

```
{
  "id": "weather-today",
  "class": "OpenWeatherDevice",
  "name": "Today",
  "location": "carlsbad, ca, usa",
  "units": "imperial",
  "lang": "en",
  "timeout": 300000
},
```

And here's what it looks like in the UI:

![image](https://cloud.githubusercontent.com/assets/698270/7760057/4f8dc4c4-ffcc-11e4-813f-95584365cd6d.png)

I sure hope it's not 60 degrees C!

**Comment by mwittig** [comment]
See also http://openweathermap.org/weather-data#current for reference

**Comment by sweetpi** [comment]
Should be solved, please reopen if there are still problems.
