### ISSUE TITLE
no update with "timeout": 3600000

### ISSUE THREAD

**Issue by lcfm1** [josecastroleon/pimatic-openweather#11]
set timeout= 1 hour. and no update. 
Add please update on start

**Comment by mwittig** [comment]
Actually, the update (@requestForecast method) is called when the device is started. Do you get any 'pimatic-openweather'  error message on startup?

**Comment by mwittig** [comment]
I have tested this and it works fine for me. Note, however, an attribute value is only updated if the new value differs from the current value. So, if the temperature does not change during the day for several hours, for example, the last updated time stamp will show the time of the last value change (past several hours).
