### ISSUE TITLE
Pimatic rules on openweather

### ISSUE THREAD

**Issue by Nears** [josecastroleon/pimatic-openweather#15]
Hi,

is it possible to add the openweather plugin into the pimatic rule set?
I tried it with the web-frontend GUI but it did not work as I want it to work ;-)

Is it possible to add a check like "if temperatur < 20°" then "turn light on" ?
If yes, how can a do that? I only gut the event changing, but a comparison to a value is not possible.

Whould be great if someone can help me out
Thanks nears

**Comment by mwittig** [comment]
Yes, that's possible. I have tested the following (see below) which works for me. As we have higher temperatures right now I have actually tested with >20 to get the rule triggered. Another setting I have tested is using the "changes" predicate, i.e., `$weather1.temperature changes`. This would trigger the rule action each time the temperature value is changed / updated. To create the rule, you can use the UI-mode as you have already tried. In the rule editor click the "condition" button and click on "attribute of a device" in the following view. Then choose "temperature" from the "Choose attribute" drop down list. Then choose the appropriate device. 

```
# Rule
{
      "id": "wetter",
      "name": "wetter",
      "rule": "if temperature of weather1 < 20 then toggle Büro Marcus: PC Lautsprecher",
      "active": true,
      "logging": true
}
# Device
{
      "id": "weather1",
      "class": "OpenWeatherDevice",
      "name": "Wetter in Julich",
      "location": "Julich, Germany",
      "units": "metric",
      "lang": "de-DE",
      "timeout": 300000
}

```
