### ISSUE TITLE
Forecast creates update with invalid data if result.list contains no data for forecast data range

### ISSUE THREAD

**Issue by mwittig** [josecastroleon/pimatic-openweather#16]
In my case the the result only contain a single foreceast record for today! See also forum thread http://forum.pimatic.org/topic/679/pimatic-openweather-openweatherforecastdevice-receives-wrong-data

**Comment by mwittig** [comment]
@josecastroleon and @sweetpi Why do we use forcecast5 rather than forecast16? Openweathermap support both, see openweathermap.daily

**Comment by n3roGit** [comment]
Maybe i have the same problem: https://github.com/pimatic/pimatic/issues/688

**Comment by sweetpi** [comment]
@mwittig Didn't know about it, is it save to just replace the name?

**Comment by mwittig** [comment]
@sweetpi No, it is a different service interface. See (Call 16 day / daily forecast data) http://openweathermap.org/forecast16 versus (Call 5 day / 3 hour forecast data) http://openweathermap.org/forecast5

I'll implement a Forecast16 device based on Pazzies code so we can trial it.

**Comment by mwittig** [comment]
@sweetpi - See https://github.com/mwittig/pimatic-openweather/tree/development-forecast16 

I have added the OpenWeatherForecast16Device for testing purposes (branch: development-forecast16)

**Comment by Nears** [comment]
Hi, 
i just updated my pimatic and its plugins. 
The openweather plugin version is now 0.8.14. 

According to https://github.com/mwittig/pimatic-openweather/tree/development-forecast16 the forecast16 has exactly this problem solved and the version name is 0.8.14.

As it is currently not well documented I changed my config.json from

```
    {
      "class": "OpenWeatherForecastDevice",
    .....
```

to 

```
    {
      "class": "OpenWeatherForecast16Device",
    .....
```

But after starting pimatic, the log tells me:

```
[pimatic] no plugin found for device "forecast" of class "OpenWeatherForecast16Device"!
```

Is there anything else to do?

**Comment by mwittig** [comment]
@Nears My fork is currently not part of the published package. To temporarily install my fork you can do as follows (assuming installation on Raspbian):

```
sudo service pimatic stop
cd /home/pi/pimatic-app/node_modules/ 
sudo rm -rf ./pimatic-openweather
git clone https://github.com/mwittig/pimatic-openweather.git
git checkout development-forecast
cd pimatic-openweather
npm install
sudo service pimatic start
```

To rollback to the released version at a later stage:

```
sudo service pimatic stop
cd /home/pi/pimatic-app/node_modules/ 
sudo rm -rf ./pimatic-openweather
npm install pimatic-openweather
sudo service pimatic start
```

**Comment by Nears** [comment]
Thanks for your reply.
But why is the new version already available in the pimatic webfrontend as new version/update?

**Comment by mwittig** [comment]
No, not yet. Due to the holiday season things are progressing slowly. I have not received much feedback on Forecast16 yet. If you are able to give it a try I'll highly appreciate this.

**Comment by Nears** [comment]
Well I tried it and a see data points now!
But I "installed" it by editing the sourcecode files of the mainline.

The only thing I see beeing wrong is that the ° characters are not displayed correctly in the pimatic web frontend. (It works for the live temperature of this plugin)

PS: I only saw the new version because it was listed in the webfrontend! Even if you didn't publish it yet.

**Comment by mwittig** [comment]
awaiting release
