### ISSUE TITLE
Cannot call method 'toFixed' of undefined

### ISSUE THREAD

**Issue by dandresm** [josecastroleon/pimatic-openweather#18]
Some locations don't provide some values, like wind speed for example. When it happens, the error "Cannot call method 'toFixed' of undefined" is fired. You can check it with town Munebrega, Spain.

Thanks in advance.

**Comment by dandresm** [comment]
It seems a problem in plugin or pimatic, because Openweathermap provides data. You can check it on this url http://openweathermap.org/city/3115913 or directly on API: http://api.openweathermap.org/data/2.5/weather?id=3115913
However the device dos not show the right data on pimatic:
![captura1](https://cloud.githubusercontent.com/assets/9026548/8780791/93ac15ac-2f0b-11e5-87be-aafa196099b8.PNG)

**Comment by mwittig** [comment]
@dandresm Thanks for poining this out. I'll have a look at it later.

**Comment by mwittig** [comment]
awaiting release

**Comment by dandresm** [comment]
Thank you very much!
