### ISSUE TITLE
Why user defined ApiKey?

### ISSUE THREAD

**Issue by Icesory** [josecastroleon/pimatic-openweather#25]
The OpenWeather team provides Api keys for Opensource Software

For FOSS developers: we welcome free and open source software and are willing to help you. If you want to use OWM data in your free software application please register an API key and file a ticket describing your application and API key registered. OWM will review your request lift access limits for your key if used in open source application.

http://openweathermap.org/faq#error401

**Comment by josecastroleon** [comment]
Do we really need to have a shared key for everyone? Why is it too difficult to request one for each of us?

**Comment by Icesory** [comment]
it is more user friendly. I know many people how have problems with setting up pimatic. 
And what is the problem with one shared key? I cant buy a washer with this key. :-)

**Comment by mwittig** [comment]
For now, I think it is ok to ask users to get their private apiKey as it is not a big hurdle. We still have the option to request a shared apiKey.

**Comment by sweetpi** [comment]
I've requested an API key for pimatic. Let's see.

**Comment by mwittig** [comment]
@sweetpi Did you receive a response from openweather?

**Comment by sweetpi** [comment]
The last response I have is:

> thank you for using our services. Your request has been submitted for inclusion in our open source support program.

But no further replay. I will ask for the status.

**Comment by mwittig** [comment]
I am closing this one as there has been no progress. I think the APIkey per user solution is good enough and has been accepted by the user base. Please re-open if you want to follow up on this.
