### ISSUE TITLE
hiding attir does not work

### ISSUE THREAD

**Issue by hamelsveld** [josecastroleon/pimatic-openweather#29]
14:39:44.772 [pimatic] error:>...0,  "lang": "en"  "xAttributeOptions":
14:39:44.772 [pimatic] error:>---------------------^
14:39:44.772 [pimatic] error:>Expecting 'EOF', '}', ':', ',', ']', got 'STRING'
14:39:44.772 [pimatic] error:>    at Object.parseError (/home/pi/pimatic-app/node_modules/pimatic/node_modules/jsonlint/lib/jsonlint.js:150:15)
14:39:44.772 [pimatic] error:>    at Object.parse (/home/pi/pimatic-app/node_modules/pimatic/node_modules/jsonlint/lib/jsonlint.js:215:22)
14:39:44.772 [pimatic] error:>    at Object.exports.parse (/home/pi/pimatic-app/node_modules/pimatic/node_modules/jsonlint/lib/jsonlint.js:665:51)
14:39:44.772 [pimatic] error:>    at Framework._loadConfig (/home/pi/pimatic-app/node_modules/pimatic/lib/framework.coffee:98:27)
14:39:44.772 [pimatic] error:>    at new Framework (/home/pi/pimatic-app/node_modules/pimatic/lib/framework.coffee:56:8)
14:39:44.772 [pimatic] error:>    at /home/pi/pimatic-app/node_modules/pimatic/startup.coffee:51:21
14:39:44.772 [pimatic] error:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:26:23)
14:39:44.772 [pimatic] error:>    at Function.Promise.attempt.Promise.try (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/method.js:31:24)
14:39:44.772 [pimatic] error:>    at Object.module.exports.startup (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:50:10)
14:39:44.772 [pimatic] error:>    at run (/home/pi/pimatic-app/node_modules/pimatic/pimatic.js:15:24)
14:39:44.772 [pimatic] error:>    at /home/pi/pimatic-app/node_modules/pimatic/lib/daemon.coffee:87:9
14:39:44.772 [pimatic] error:>    at Object.oncomplete (fs.js:107:15)
14:39:44.776 [pimatic] info: exiting...

this is what I get if I use the example from your manual... any tips?

**Comment by mwittig** [comment]
Hi, I think there is a comma missing before "xAttributeOptions". I am going to fix this as part of the README. Please let me know if this solves your problem.

**Comment by hamelsveld** [comment]
Yuup looks like its working :-)

**Comment by mwittig** [comment]
Great! I am closing this now.
