### ISSUE TITLE
windspeed metric unit

### ISSUE THREAD

**Issue by timovp** [josecastroleon/pimatic-openweather#3]
I think the windspeed unit should be m/s, [source](https://openweathermap.desk.com/customer/portal/questions/8324584-wind-unit-of-measurement-for-metric-), when you choose metric units. 
When I use it now it says km/h. Hope this helps.
Secondary question, is there a way to show less information when I add the device to a page? (snow for instance is not really relevant in the Netherlands)

**Comment by mwittig** [comment]
Windspeed unit has been fixed in 0.8.6.

@timovp Regarding your question about hinding attributes this is now possible using the xAttributeOptions feature. See the following example.

``` javascript
{
      "id": "weather",
      "class": "OpenWeatherDevice",
      "name": "Wetter in Potsdam",
      "location": "Potsdam, Germany",
      "lang": "de",
      "units": "metric",
      "timeout": 300000,
      "xAttributeOptions": [
           {
               "name": "snow",
               "hidden": true
           }
      ]
}
```
