### ISSUE TITLE
LocationId=2759794 VS Location=Amsterdam, NL in solving errors?

### ISSUE THREAD

**Issue by pimagical** [josecastroleon/pimatic-openweather#30]
Sometimes i get an error location not found. I was wondering how this is possible and if the current location name is responsible for this? Could an extra locationId field or replacing the current location with a locationId give help to solve the errors?

Location=Amsterdam, NL 
LocationId=2759794

http://openweathermap.org/city/2759794

**Comment by mwittig** [comment]
Possibly. I am also having issues at the moment. In my setup I am getting false values now and then. Investigating this, I noticed the values change depending on how the service is queried (variations of the query which all match the same location). I think it is bug, but openweather.org is denying it so far.

As a work-around we can try using the locationId. Maybe this will work better - without intermittent outliers or "not found" error messages in your case.  I'll setop a separate branch for this and keep you posted.

**Comment by pimagical** [comment]
Nice! Just let me know how i could participate in testing the branch.

**Comment by mwittig** [comment]
Sorry for the delay. Released with v0.9.0
