### ISSUE TITLE
Sometimes Value of Rain is Unkown

### ISSUE THREAD

**Issue by Wikibear** [josecastroleon/pimatic-openweather#31]
Sometimes value of rain is unkown. Seems to be not set String something like this:

![unbenannt](https://cloud.githubusercontent.com/assets/18314278/17147099/77de00c6-5361-11e6-8ac5-37c8963c7904.PNG)

**Comment by mwittig** [comment]
Yes, that normal behaviour as far as the openweather service is concerned. The plugin should only set the value to "unknown" if there is not previous value set. I'll have a look at this soon.

**Comment by mwittig** [comment]
Works as designed
