### ISSUE TITLE
Feature request: Include status-id in device attributes

### ISSUE THREAD

**Issue by ruegr** [josecastroleon/pimatic-openweather#37]
It would be really cool, if you created a new device attribute for the id of the weather status and maybe also the 'main' category as provided by the openweathermap-api:
`    "weather": [
        {
            "id": 500,
            "main": "Rain",
            "description": "light rain",
            "icon": "10n"
        }`

Especially the id is probably not an eye-catcher for the GUI, but it would help really much to use the weather-status for rules etc.

Thanks a lot!

**Comment by ruegr** [comment]
Although I'm not used with coffeescript I could include these two attributes on my own.
The changed 'openweather.coffee' works like charm in my pimatic!

**Comment by mwittig** [comment]
Excellent! Thanks for your contribution! We should also add some documentation for the new attributes.

Shouldn't we add the same attributes for Forecast?

**Comment by ruegr** [comment]
Thanks! Feels great not just to use oss but also contribute to it :-)

I'm not using the forecast, but when the same information is provided by owm-api it seems like a good idea.

The different codes are explained here: https://openweathermap.org/weather-conditions
I'm using these to display a proper icon from the WeatherIcon-Font (https://erikflowers.github.io/weather-icons/) - fortunately those are direct compatible (there are icons like wi_owm_800 for openweathermap-status 800). Maybe this would also be an improvement for the mobile-gui of pimatic?

Pull-Request for documentation: https://github.com/josecastroleon/pimatic-openweather/pull/39
