### ISSUE TITLE
Error [pimatic-openweather]: invalid character

### ISSUE THREAD

**Issue by pimagical** [josecastroleon/pimatic-openweather#8]
Error after every service restart.

2015-05-12 22:03:34error [pimatic-openweather]: invalid character '<' looking for beginning of value (500)

![fullsizerender](https://cloud.githubusercontent.com/assets/11790664/7677936/75ff25ea-fd50-11e4-9b98-f00338e6586a.jpg)

**Comment by sweetpi** [comment]
This is probably fixes with https://github.com/josecastroleon/pimatic-openweather/commit/0bda28e4d31e25081aacbf0cad077af083f0d99b
